### ISSUE TITLE
是不是应该添加相互补全的功能

### ISSUE THREAD

**Issue by yangfeng20** [Pwhxbdk/swagger-tool#10]
doc->swagger
swagger->doc
还有空字符串就不转换了
还有公共父类一般是不能改变的，是否可以选择不改变父类呢

**Comment by Pwhxbdk** [comment]
1.得评估一下swagger->doc 转换的必要性。
2.第二个问题，对Model类生成swagger注解的时候希望父类不被影响。

**Comment by Pwhxbdk** [comment]
@yangfeng20 请问什么场景下需要 swagger->doc 这种转换类型呢？

**Comment by yangfeng20** [comment]
就是有些人注释写的很烂啊，可能有doc，没有swagger；有swagger，没有doc；我的意思是说只需要他们其中一个缺失，就把另外一个补全。但是空字符最后就忽略掉。

**Comment by Pwhxbdk** [comment]
doc注释这应该是属于代码规范的管理内容了吧，注释写的很烂就要求他把注释写好😁

**Comment by yangfeng20** [comment]
那我觉得空字符串的问题可以解决一下😁，还有不要去更新父类，或者添加一个开关

**Comment by Pwhxbdk** [comment]
空字符串问题可以详细描述一下吗

**Comment by yangfeng20** [comment]
![image](https://user-images.githubusercontent.com/83114564/200246560-cf48d970-42ce-4d26-a822-a1b42aa8ebbc.png)

**Comment by Pwhxbdk** [comment]
这种空的doc注释或者没有任何doc注释的情况生成一个空注解是为了提醒开发者填入对应说明，还有一种情况就是开发者并不想在swagger文档中显示此属性，也可以改为生成 @ApiModelProperty(hidden = true)

**Comment by yangfeng20** [comment]
行，可以的
