### ISSUE TITLE
springfox已经好久没更新了。

### ISSUE THREAD

**Issue by hL-ab** [Pwhxbdk/swagger-tool#12]
插件可以支持springdoc吗？

**Comment by Pwhxbdk** [comment]
@hL-ab 之前由于Swagger 3（OpenAPI 3）部分注解不生效，所以没有对新注解生成进行更新。没考虑SpringDoc用户的使用度， 我试一下SpringDoc使用效果，如果可以我会尽快加入更新计划。感谢关注！

**Comment by Pwhxbdk** [comment]
新版本已更新，加入了Swagger 3注解生成。
