### ISSUE TITLE
开发问题请求

### ISSUE THREAD

**Issue by raystart** [Pwhxbdk/swagger-tool#14]
项目没有pom或者grade文件怎么打包的？ 依赖怎么引入的呢

**Comment by Pwhxbdk** [comment]
你的项目没有使用maven或者gradle来管理依赖吗？

**Comment by raystart** [comment]
我是问你这个插件项目，没有看到pom 也没有grade  好奇咋打包的

**Comment by Pwhxbdk** [comment]
我理解错了，这个插件项目很简单，没有而外依赖其他的jar，仅仅使用了IDEA IntelliJ Platform Plugin SDK。如果你想知道如何在IDEA插件项目中引入其他依赖可以参考Lombok这个项目。

**Comment by Pwhxbdk** [comment]
我理解错了，这个插件项目很简单，没有额外依赖其他的jar，仅仅使用了IDEA IntelliJ Platform Plugin SDK。如果你想知道如何在IDEA插件项目中引入其他依赖可以参考Lombok这个项目。

**Comment by raystart** [comment]
ok 感谢 我学习下
