### ISSUE TITLE
使用SwaggerAnnotation 3.x生成注解时会将类上的@RequestMapping("/user/live/session/comment")路径覆盖到@Tag(name = "/user/live/session/comment"）的name上面。

### ISSUE THREAD

**Issue by hialuoy** [Pwhxbdk/swagger-tool#15]
使用SwaggerAnnotation 3.x生成注解时会将类上的@RequestMapping("/user/live/session/comment")路径覆盖到@Tag(name = "/user/live/session/comment"）的name上面。

![1685355810814](https://github.com/Pwhxbdk/swagger-tool/assets/64819817/b79bf399-1585-482a-b93a-5dbe23c1d8df)

**Comment by Pwhxbdk** [comment]
其实这个name和description区别不是很大，要么填充一样的内容，要么把name去掉。

**Comment by hialuoy** [comment]
> 其实这个name和description区别不是很大，要么填充一样的内容，要么把name去掉。

我没用过原生的swagger和spring rest doc我用的是knife4j因为knife4j会把@tag() name属性解析成接口分组的名称。不知道原生展示是用的哪一属性。我建议您可以填充一样的内容。

**Comment by Pwhxbdk** [comment]
可以，感谢你的建议
