### ISSUE TITLE
希望没有@GetMapping等注解的方法不生成swagger/springdoc注解

### ISSUE THREAD

**Issue by wisetim** [Pwhxbdk/swagger-tool#18]
尤其是构造方法

原始方法：
<img width="413" alt="image" src="https://github.com/Pwhxbdk/swagger-tool/assets/32615099/c98dcbde-2dda-4d49-a510-04d6247dc110">
生成之后：
<img width="764" alt="image" src="https://github.com/Pwhxbdk/swagger-tool/assets/32615099/1ccda3e3-ebdb-4c6c-9983-ffbfef059502">

**Comment by Pwhxbdk** [comment]
确实是bug
