### ISSUE TITLE
反馈两个问题

### ISSUE THREAD

**Issue by Dlinw** [Pwhxbdk/swagger-tool#19]
工具很好用，但用着发现了些问题：
1、
现在会重复覆盖生成。希望增加两个选项，一个是覆盖生成、一个是增量生成。
2、
没有javadoc的字段在生成注解时会标记为hidden，这有些不方便。另外由于“覆盖生成”也导致没有写javadoc的字段，但已经补充了描述，在想生成其他字段的注解时就会背覆盖掉。

我记得以前都没有这些问题的，突然就有了。目前使用的是swagger3注解。

**Comment by Pwhxbdk** [comment]
没有javadoc的字段之前考虑是有些开发者确实不想让这个字段出现在swagger文档里面。
现在我将“重复覆盖生成”问题添加到修复计划中。
