### ISSUE TITLE
Controller层@ApiOperation只有第一个方法有，之后的方法没生成对应注解，且value和notes为空

### ISSUE THREAD

**Issue by bennick1** [Pwhxbdk/swagger-tool#2]
当前：
@ApiOperation(value = "", notes = "", httpMethod = "POST")
public String a1() {}

public String a2() {}

=================================
希望改进：
@ApiOperation(value = "/a1", notes = "xxx1", httpMethod = "POST")
public String a1() {}
@ApiOperation(value = "/a2", notes = "xxx2", httpMethod = "POST")
public String a2() {}

**Comment by Pwhxbdk** [comment]
修改了只有一个方法的bug，会在新发布的1.0.6版本中更新，但是关于ApiOperation注解中value和notes属性的值这个应该属于您具体业务的范畴了，插件生成无法给出一个默认值，如果您有更好的想法，欢迎提出交流，谢谢。
