### ISSUE TITLE
需要为数组参数添加 allowMultiple=true 修饰!

### ISSUE THREAD

**Issue by 0MirageTank0** [Pwhxbdk/swagger-tool#20]
如题!非常强大的插件,但缺少对于数组类型的参数识别:
比如如下的接口

    @GetMapping("/post/lists/{ids}")
    public List<DcmApplicationPost> listArray(@PathVariable("ids") Long [] ids)

自动生成的是

    @ApiImplicitParams({
            @ApiImplicitParam(paramType = "path",dataType = "Long[]", name = "ids", value = "", required = true)
    })
    @ApiOperation(value = "获取详情信息", notes = "获取详情信息", httpMethod = "GET")
    @GetMapping("/post/lists/{ids}")
    public List<DcmApplicationPost> listArray(@PathVariable("ids") Long [] ids)

实际上正确的是

    @ApiImplicitParams({
            @ApiImplicitParam(paramType = "path",allowMultiple = true, dataType = "Long", name = "ids", value = "", required = true)
    })
    @ApiOperation(value = "获取详情信息", notes = "获取详情信息", httpMethod = "GET")
    @GetMapping("/post/lists/{ids}")
    public List<DcmApplicationPost> listArray(@PathVariable("ids") Long [] ids)

也就是加上了allowMultiple=true,去除了dataType后的[] !

**Comment by Pwhxbdk** [comment]
感谢你的issue，后续版本中会更新此问题。
