### ISSUE TITLE
最近一次更新之后，可能是版本原因，插件无法编译成功了。

### ISSUE THREAD

**Issue by guchengcc** [Pwhxbdk/swagger-tool#22]
com.intellij.diagnostic.PluginException: Cannot load class com.pwhxbdk.swaggertool.SwaggerTool3 (
  error: com/pwhxbdk/swaggertool/SwaggerTool3 has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Swagger Tools, id=com.pwhxbdk.plugin.swagger.tool, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2021.2\plugins\swagger-tool-1.2.5.jar, version=1.2.5, package=null), packagePrefix=null, instanceId=73, state=active)
)

我这边项目使用的是8的版本。
希望大佬有时间可以看一下~
![Snipaste_2023-12-19_09-29-47](https://github.com/Pwhxbdk/swagger-tool/assets/126763426/0876b0bc-98bd-4dbe-9b53-36be58c4afe2)

**Comment by Pwhxbdk** [comment]
“构建项目的 JVM 语言级别对于 2020.3+ 使用 Java 11，对于 2022.2+ 使用 Java 17”。 你在Project Structure 新增一个JDK11再试试。

**Comment by guchengcc** [comment]
![image](https://github.com/Pwhxbdk/swagger-tool/assets/126763426/49717e6a-9450-4b8a-8a3e-8728da7a040c)
我将项目切换为jdk11之后还是出现相同的问题，这个会是什么原因呢

**Comment by Pwhxbdk** [comment]
我试了一下21版本，确实是有一些问题，需要等下一个版本升级。
目前解决办法需要将IDEA升级到23版本。
感谢你的issue

**Comment by Pwhxbdk** [comment]
<img width="950" alt="image" src="https://github.com/Pwhxbdk/swagger-tool/assets/39589778/963a74ba-8102-40e6-b22d-8d27e0be3702">
改一下这个选项试试

**Comment by Pwhxbdk** [comment]
新版本1.2.6修改了无法编译的问题
