### ISSUE TITLE
请问能屏蔽serialVersionUID的注解生成吗

### ISSUE THREAD

**Issue by zhangs1611** [Pwhxbdk/swagger-tool#23]
目前存在serialVersionUID时，会自动添加一个注解，但不想要
![1705461628436](https://github.com/Pwhxbdk/swagger-tool/assets/93459289/3b3f054c-ce86-4735-a357-6abce0208215)

**Comment by Pwhxbdk** [comment]
好的，感谢你的issue，改动会在下个版本更新
