### ISSUE TITLE
生成的@ApiImplicitParams注解会导致swagger接口文档展示错误

### ISSUE THREAD

**Issue by serpmelon** [Pwhxbdk/swagger-tool#25]
对于对象参数@ RequestBody, 会自动生成@ ApiImplicitParams注解, 但是在swagger文档中查看参数只展示一个string, 如图, 删除掉这个注解会正常展示对象参数.
![image](https://github.com/user-attachments/assets/6a0644cc-19df-4463-862a-14eeefd13e7e)

使用的是swagger2.0

**Comment by serpmelon** [comment]
指定dataTypeClass就可以正常展示了

**Comment by Pwhxbdk** [comment]
可以看一下你的Controller以及生成后的代码吗？

**Comment by serpmelon** [comment]
![image](https://github.com/user-attachments/assets/c5437093-80e6-4a5c-96ae-91be89a4f1dc)
这个是自动生成的代码, 在swagger中会展示为一个string类型的form. 指定dataTypeClass后就可以正常展示了

**Comment by Pwhxbdk** [comment]
我这边按照你的案例没法重现，你检查一下swagger版本。

**Comment by serpmelon** [comment]
修改了swagger版本后好了 感谢
