### ISSUE TITLE
希望能支持 swagger 3 即 OpenAPI 的注解

### ISSUE THREAD

**Issue by cn-src** [Pwhxbdk/swagger-tool#4]

**Comment by Pwhxbdk** [comment]
我研究一下

**Comment by Pwhxbdk** [comment]
目前swagger3部分注解不生效（应该是BUG），如@Tag注解在Controller上，@Schema 注解在Model上，@Parameters注解在方法上。除非是swagger3注解和swagger2注解参杂着一起用，所以目前暂不做swagger3更新。感谢关注！
