### ISSUE TITLE
请问如何使用

### ISSUE THREAD

**Issue by xujimu** [Pwhxbdk/swagger-tool#6]
![搜狗截图20220822094153](https://user-images.githubusercontent.com/61351674/185822667-d764e72a-1ab2-43ed-98ff-4a9d36d3f640.png)
我安装了插件 不知道该如何使用 麻烦指点下 谢谢

**Comment by Pwhxbdk** [comment]
直接按 Alt + Insert 然后选择 SwaggerAnntation 就可以了

**Comment by xujimu** [comment]
> 

ok谢谢，给个建议哈，一般我们都是mybatisX 构建表实体，表实体一般会带上表字段的注释，然后每次我都需要手动加上@ApiModelProperty我看目前咱们的插件只是单一的，可以考虑出一个批量的，就是选中类名称，一键生成所有字段的swgger注解，因为如果是单一的话一个一个字段去添加其实和复制粘贴效率差不多，有注释的就生成，没注释的就生成value=“”然后自己去填写不是更方便一点嘛

**Comment by Pwhxbdk** [comment]
直接在空白处右键选择 Generate... 再选择 SwaggerAnntation 就会生成全部了
